name: Build Dependencies

on: [ push, pull_request ]

jobs:
  build:
    name: Building windows deps
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3.1.0

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.12.0

      - name: Configure
        run: cmake .

      - name: Build
        run: msbuild /p:Configuration=Release /m ror-dependencies.sln

      - name: Upload deps folder
        uses: actions/upload-artifact@v3
        with:
          name: Dependencies_Windows
          path: Dependencies_Windows_Visual-Studio-16-2019